;
; File generated by cc65 v 2.19 - Git 30dc9b8d1
;
	.fopt		compiler,"cc65 v 2.19 - Git 30dc9b8d1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "src/main.c", 279, 1653851078
	.dbg		file, "/home/andrea/local/share/cc65/include/stdio.h", 6742, 1654375703
	.forceimport	__STARTUP__
	.dbg		sym, "printf", "00", extern, "_printf"
	.import		_printf
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$48,$65,$6C,$6C,$6F,$20,$77,$6F,$72,$6C,$64,$0A,$00
S0002:
	.byte	$41,$20,$3D,$20,$25,$64,$0A,$00
S0003:
	.byte	$44,$6F,$6E,$65,$0A,$00

; ---------------------------------------------------------------
; int __near__ some (int a)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_some: near

	.dbg	func, "some", "00", static, "_some"
	.dbg	sym, "a", "00", auto, 0
	.dbg	sym, "b", "00", auto, -2

.segment	"CODE"

	.dbg	line, "src/main.c", 4
	jsr     pushax
	.dbg	line, "src/main.c", 5
	ldx     #$00
	lda     #$08
	jsr     pushax
	.dbg	line, "src/main.c", 6
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxysp
	.dbg	line, "src/main.c", 7
	ldy     #$01
	jsr     ldaxysp
	jmp     L0001
	.dbg	line, "src/main.c", 8
L0001:	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; unsigned char __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "a", "00", auto, -2

.segment	"CODE"

	.dbg	line, "src/main.c", 13
	jsr     decsp2
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	.dbg	line, "src/main.c", 15
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0002:	ldy     #$01
	jsr     ldaxysp
	cmp     #$0A
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0005
	jmp     L0003
	.dbg	line, "src/main.c", 17
L0005:	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _some
	jsr     pushax
	ldy     #$04
	jsr     _printf
	.dbg	line, "src/main.c", 15
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
	.dbg	line, "src/main.c", 20
L0003:	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	.dbg	line, "src/main.c", 22
	ldx     #$00
	lda     #$00
	jmp     L0001
	.dbg	line, "src/main.c", 23
L0001:	jsr     incsp2
	rts

	.dbg	line
.endproc

