name: Check

on:
  pull_request:
    branches:
        - master
  workflow_dispatch:
      inputs:
          ref:
              description: The git refspec to checkout
              required: true
              default: 'master'

jobs:
  kill_old_jobs:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  mac-build:

    runs-on: macos-10.15
    #container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      fail-fast: false
      matrix:
          include:
              - vice_version: ""
                vice_directory: VICE_DIRECTORY=

    steps:
    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"
    - run: brew install vice
    - run: npm install -g pnpm
    - run: pnpm install --shamefully-hoist
    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} pnpm build:test
    - continue-on-error: true
      run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm testmerge

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "Test Results: Mac: VICE ${{ matrix.vice_version }}"
        path: "*.testrun.xml"
        reporter: jest-junit

  linux-build:
    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
          ./**/*
        key: check-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}

    - uses: actions/checkout@v2
      with:
          ref: "${{ github.events.inputs.ref }}"

    - run: pnpm install --shamefully-hoist
    - run: ln -s $PWD/system /usr/local/share/vice
    - run: ln -s $PWD/system /usr/local/lib/vice
    - run: ln -s $PWD/system /usr/lib/vice
    - run: ln -s $PWD/system /usr/share/vice
    - run: ls -l /usr/local/share
    - run: pnpm build:test

  linux-test:
    needs: linux-build
    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    strategy:
      fail-fast: false
      matrix:
          include:
              - vice_version: 3.5
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.5/src
              - vice_version: 3.6
                vice_directory: VICE_DIRECTORY=/vices/builds/vice-3.6/src
              - vice_version: trunk
                vice_directory:

    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
          ./**/*
        key: check-${{ runner.os }}-${{ github.run_id }}-${{ github.run_number }}

    - run: VICE_SVN_VERSION=${{ matrix.vice_version }} ${{ matrix.vice_directory }} USE_XVFB=1 pnpm testmerge

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: "Test Results: Linux: VICE ${{ matrix.vice_version }}"
        path: "*.testrun.xml"
        reporter: jest-junit
