name: Docker

on:
  push:
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
      name: Checkout Code
      with:
          ref: master
    - run: cd docker && docker build -t empathicqubit/vscode-cc65-debugger-build .
    - run: cd docker && docker build -t empathicqubit/vscode-cc65-debugger-devcontainer -f devcontainer.Dockerfile .
    - run: docker push empathicqubit/vscode-cc65-debugger-build
    - run: docker push empathicqubit/vscode-cc65-debugger-devcontainer
