name: Trash

on:
    workflow_dispatch:
        inputs:
            tag:
                description: The git tag to checkout
                required: true
                default: 'refs/tags/vFIXME'

jobs:
  build:

    runs-on: ubuntu-18.04
    container: empathicqubit/vscode-cc65-debugger-build

    steps:
    - run: echo "Hallo Leute" > testerson.txt